name: Feature request
description: Suggest an idea for this project
body:
  - type: markdown
    attributes:
      value: Please be as detailed as possible so that we may consider and review the request easier. We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Please give some context for this request. Why do you want it added?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: List any alternatives you might have tried to get the feature you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add any other context or screenshots about the feature request below.
    validations:
      required: false

  - type: markdown
    attributes:
      value: Before submitting this feature request, please search our issue tracker to ensure your feature has not already been requested.
