name: Maven

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  MAVEN_CLI_OPTS: -Pci-cd -B -C -U --fail-at-end --show-version -e

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Useful for SonarCloud Scans
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build & Test
        run: mvn ${{ env.MAVEN_CLI_OPTS }} install
      - name: SonarCloud Quality Scan
        run: mvn sonar:sonar -Dsonar.projectKey=Djaytan_bukkit-slf4j
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
