name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release-perform:
    name: Release - Perform
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    permissions:
      contents: write # Required to publish a GitHub release
      issues: write # Required to comment on released issues
      pull-requests: write # Required to comment on released pull requests

    env:
      CHANGELOG_FILE: ${{ github.workspace }}/docs/CHANGELOG.md

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            repo.maven.apache.org:443
            central.sonatype.com:443
            jitpack.io:443
            repo.papermc.io:443
            api.nuget.org:443
            registry.npmjs.org:443

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0 # Required by semantic-release

      - name: Config Git user as release bot
        env:
          # https://github.com/orgs/community/discussions/26560#discussioncomment-3252339
          RELEASE_BOT_NAME: 'github-actions[bot]'
          RELEASE_BOT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        run: |
          git config --global user.name "${RELEASE_BOT_NAME}"
          git config --global user.email "${RELEASE_BOT_EMAIL}"

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/iron
          cache: npm
          cache-dependency-path: .github/package-lock.json

      - name: Install semantic-release
        working-directory: .github/
        run: npm clean-install

      - name: Setup Java
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Maven releasing-related properties
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          # Hacky way of retrieving the released version tag name through a temporary file
          TMP_TAG_VERSION_NAME_FILE: ${{ runner.temp }}/tag_version_name
        working-directory: .github/
        run: |
          npx --no-install semantic-release
          echo "tag=$(cat "${TMP_TAG_VERSION_NAME_FILE}")" >> "${GITHUB_OUTPUT}"

      - name: Create a PR for creating/updating the changelog file
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CHANGELOG_BRANCH_NAME: changelog/${{ steps.release.outputs.tag }}
        run: |
          git switch --create "${CHANGELOG_BRANCH_NAME}"
          git add "${CHANGELOG_FILE}"
          git commit --message='docs(changelog): release ${{ steps.release.outputs.tag }}' "${CHANGELOG_FILE}"
          git push --set-upstream origin "${CHANGELOG_BRANCH_NAME}"

          gh pr create --fill \
            --label 't:release' \
            --base ${{ github.ref_name }} \
            --head "${CHANGELOG_BRANCH_NAME}"
